### ISSUE TITLE
Releases / Tags?

### ISSUE THREAD

**Issue by jtaleric** [datastax-labs/hunter#15]
Any chance we could cut a release for folks to pin to?

**Comment by jtaleric** [comment]
/assign @smccarthy788  

(not sure this will work)

**Comment by smccarthy788** [comment]
> (not sure this will work)

I got an email, maybe that counts 🤷

I see the Orion thread about not wanting to pin to a sha. Reasonable, but please keep in mind all work on this repo is ad-hoc & voluntary. I've cut a `v0.5.0` tag, but make no promises about future tags or releases.

**Comment by jtaleric** [comment]
@smccarthy788 totally understand! Let me know if you need more volunteers to help things along! Thanks!!
