### ISSUE TITLE
Upgrade numpy version as 1.19.0 is too old

### ISSUE THREAD

**Issue by omartoutounji** [datastax-labs/hunter#9]
On macOS running on Apple Silicon, version 1.19.0 of numpy no longer works as it is too old. More information can be found here on [this issue in the numpy repo](https://github.com/numpy/numpy/issues/22477). I went through this problem and couldn't install hunter due to it so I tried upgrading numpy and things work with tests passing so I propose upgrading numpy to version 1.26.1 and python to ">=3.9,<3.13" to support the change.

**Comment by omartoutounji** [comment]
I have a PR ready, is there any way I can be invited as a collaborator to this repo so I can push it? @guyboltonking @pkolaczk @henrikingo @smccarthy788

**Comment by henrikingo** [comment]
Hi and that's great to hear!

You don't need to have any special permission to submit a PR. Please use the workflow where you fork your own repo, push your branch there, then create a pr against this repo
https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by omartoutounji** [comment]
Looks like it got updated here https://github.com/datastax-labs/hunter/commit/5a7a361dc9251bfed95ef9537d073cb06b645aaa
